project:
  type: website

website:
    navbar: 
      title: "IS415 Journey" 
      left:
        - text: Overview
          href: index.qmd
        - text: Hands-On Exercise
          menu:
            - text: Hands-On Exercise 1
              href: hoe1.qmd
        - text: In-Class Exercise
          menu:
            - text: In-Class Exercise 1
              href: ice1.qmd
        - text: Take-Home Exercise
          menu:
            - text: Take-Home Exercise 1
              href: the1.qmd
              
format:
  html:
    theme:
      light: flatly
      dark: darkly
    linkcolor: rgb(0, 153, 255)
    toc: true