project:
  type: website

website:
  favicon: "/pictures/favicon.jpg"
  navbar:
    logo: ""
    title: "Chi Hao's IS415 Journey" 
    left:
      - text: Overview
        href: index.html #reference to HTML file instead of qmd
      - text: Hands-On Exercise
        menu:
          - text: Hands-On Exercise 1
            href: "Hands-On_Ex/Hands-On_Ex01/hoe01.html"
          - text: Hands-On Exercise 2
            href: "Hands-On_Ex/Hands-On_Ex02/hoe02.html"
          - text: Hands-On Exercise 3
            href: "Hands-On_Ex/Hands-On_Ex03/hoe03.html"    
          - text: Hands-On Exercise 5
            href: "Hands-On_Ex/Hands-On_Ex05/hoe05.html"
          - text: Hands-On Exercise 6a
            href: "Hands-On_Ex/Hands-On_Ex06/hoe06a.html"  
          - text: Hands-On Exercise 6b
            href: "Hands-On_Ex/Hands-On_Ex06/hoe06b.html"
      - text: In-Class Exercise
        menu:
          - text: In-Class Exercise 2
            href: "In-Class_Ex/In-Class_Ex02/ice02.html"
          - text: In-Class Exercise 3
            href: "In-Class_Ex/In-Class_Ex03/ice03.html"
          - text: In-Class Exercise 4
            href: "In-Class_Ex/In-Class_Ex04/ice04.html"
          - text: In-Class Exercise 5
            href: "In-Class_Ex/In-Class_Ex05/ice05.html"

      - text: Take-Home Exercise
        menu:
          - text: Take-Home Exercise 1
            href: "Take-Home_Ex/Take-Home_Ex01/the01.html"
          - text: Take-Home Exercise 2
            href: "Take-Home_Ex/Take-Home_Ex02/the02.html"
          - text: Take-Home Exercise 3
            href: "Take-Home_Ex/Take-Home_Ex03/the03.html"
format:
  html:
    theme:
      light: flatly
      dark: darkly
    linkcolor: rgb(0, 153, 255)
    toc: true